name: Eslint Checker
on: [pull_request]
jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node.js modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.OS }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --ignore-scripts
      - name: Run ESLint
        run: yarn run lint
